name: example

on: push

jobs: 
  first_job:
        runs-on: ubuntu:latest
        steps: 
            - name: welcome-script
              run: echo "my first hello message via ci/cd"

            - name: files
              run: ls -a
            
            
