name: example

on: push

jobs: 
  first_job:
        runs-on: macos-latest

        steps: 
            - name: welcome-script
              run: echo "my first hello message via ci/cd pipeline"

            - name: files
              run: ls -a
            
            
